export const data = {
  data: {
    A1: {
      category: 'sale',
      type: 'sedan',
      color: ['red', 'green', 'yellow'],
      createDate: '2022-09-20 15:50+00Z',
      price: 300,
      moneyType: 'USD',
      capacity: 2,
      timeType: null,
    },
    A2: {
      category: 'rental',
      type: 'suv',
      color: ['red', 'green'],
      createDate: '2019-10-14 15:50+00Z',
      price: 15,
      moneyType: 'BS',
      capacity: 3,
      timeType: 'month',
    },
    A3: {
      category: 'sale',
      type: 'van',
      color: ['green', 'yellow'],
      createDate: '2019-09-10 15:50+00Z',
      price: 45,
      moneyType: 'USD',
      capacity: 5,
      timeType: null,
    },
    A4: {
      category: 'rental',
      type: 'truck',
      color: ['yellow'],
      createDate: '2019-12-07 15:50+00Z',
      price: 21000,
      moneyType: 'USD',
      capacity: 6,
      timeType: 'day',
    },
    A5: {
      category: 'sale',
      type: 'mazda',
      color: ['red', 'yellow'],
      createDate: '2019-09-07 15:50+00Z',
      price: 34000,
      moneyType: 'BS',
      capacity: 3,
      timeType: null,
    },
    A6: {
      category: 'rental',
      type: 'porsche',
      color: ['red', 'green'],
      createDate: '2019-09-21 15:50+00Z',
      price: 34,
      moneyType: 'BS',
      capacity: 5,
      timeType: 'year',
    },
    A7: {
      category: 'sale',
      type: 'ferrari',
      color: ['yellow'],
      createDate: '2000-09-07 15:50+00Z',
      price: 56,
      moneyType: 'USD',
      capacity: 3,
      timeType: null,
    },
    A8: {
      category: 'sale',
      type: 'lexus',
      color: ['red', 'yellow'],
      createDate: '2022-02-07 15:50+00Z',
      price: 70,
      moneyType: 'BS',
      capacity: 3,
      timeType: '',
    },
    A9: {
      category: 'sale',
      type: 'honda',
      color: ['red', 'green'],
      createDate: '2019-01-07 15:50+00Z',
      price: 100,
      moneyType: 'USD',
      capacity: 5,
      timeType: null,
    },
    A10: {
      category: 'rental',
      type: 'volvo',
      color: ['red', 'green'],
      createDate: '2021-09-07 15:50+00Z',
      price: 12,
      moneyType: 'USD',
      capacity: 4,
      timeType: 'month',
    },
  },
};
